version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ['react', 'vue']
  dialect = 'flow'

[[transformers]]
    name = "prettier"
    enabled = true

[[analyzers]]
name = "secrets"
enabled = true
