version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ['react', 'vue']
  dialect = 'flow'
  dependency_file_paths = [
    'packages/demo-react/',
    'packages/demo-vue/',
    'packages/demo-next/',
    'packages/demo-nuxt/',
    'packages/demo-typescript/'
  ]
  skip_doc_coverage = ['function-declaration', 'function-expression', 'arrow-function-expression', 'class-declaration', 'class-expression', 'method-definition']

[[transformers]]
    name = "prettier"
    enabled = true

[[analyzers]]
name = "secrets"
enabled = true
